server:
  port: 9094
spring:
  application:
    name: supergo-manager
  datasource:
    url: jdbc:mysql://localhost:3306/supergo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver #sql驱动
    type: com.alibaba.druid.pool.DruidDataSource #指定数据源类型
    druid:
      initial-size: 5 # 初始连接数
      min-idle: 5 # 最小空闲连接数
      max-active: 20 # 最大活动连接数
      max-wait: 1000 # 连接的(超时)最大等待时间
  servlet:
    multipart:
      max-file-size: 5MB # 最大文件上传大小
  boot:
    admin:
      client:
        url: http://127.0.0.1:9876 # 监控中心地址
  redis:
    host: localhost # 指定redis的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka # eureka注册中心地址
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /api/actuator/health #网关设置了根路径，默认监控路径发生了变化
mybatis:
  type-aliases-package: com.supergo.pojo
  mapper-locations: classpath:mapper/*Mapper.xml # 指定Mapper.xml文件的位置
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  config:
    key: kaikeba
    #单位：秒
    ttl: 3600