server:
  port: 9109
spring:
  application:
    name: supergo-search
  datasource:
    url: jdbc:mysql://localhost:3306/supergo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver #sql驱动
    type: com.alibaba.druid.pool.DruidDataSource #指定数据源类型
    druid:
      initial-size: 5 # 初始连接数
      min-idle: 5 # 最小空闲连接数
      max-active: 20 # 最大活动连接数
      max-wait: 1000 # 连接的(超时)最大等待时间
  data:
    elasticsearch: # springData ES 配置
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"