server:
  port: 9999

spring:
  application:
    name: supergo-zuul #指定服务名
zuul: # 网关配置
  routes: # 路由配置
    supergo-manager: /service/**
    supergo-manager-web: /manager/**  # 配置方式1: 简易配置  格式: 微服务名称: 映射路径
    supergo-portal-web: /portal/**
#    manager-web: # 配置方式2: 完整配置
#      path: /manager/** # 这里是映射路径
#      serviceId: supergo-manager-web #服务的名称
  retryable: true # 转发失败是否重试
  sensitive-headers:  #请求头跨系统发送token秘钥
  host:
    connect-timeout-millis: 50000  # 各种超时时间
    socket-timeout-millis: 50000
    connection-request-timeout-millis: 50000
  boot:
    admin:
      client:
        url: http://127.0.0.1:9876 # 监控中心地址
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /api/actuator/health #网关设置了根路径，默认监控路径发生了变化
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
