server:
  port: 9094
spring:
  application:
    name: supergo-manager
  datasource:
    url: jdbc:mysql://localhost:3306/supergo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver #sql驱动
    type: com.alibaba.druid.pool.DruidDataSource #指定数据源类型
    druid:
      initial-size: 5 # 初始连接数
      min-idle: 5 # 最小空闲连接数
      max-active: 20 # 最大活动连接数
      max-wait: 1000 # 连接的(超时)最大等待时间
  servlet:
    multipart:
      max-file-size: 5MB # 最大文件上传大小
mybatis:
  type-aliases-package: com.supergo.pojo
  mapper-locations: classpath:mapper/*Mapper.xml # 指定Mapper.xml文件的位置
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  config:
    key: kaikeba
    #单位：秒
    ttl: 3600